base/Dockerfile, base/build.json
Upgrades the add-on base image to 9.0.0.
Changelog: <https://github.com/hassio-addons/addon-base/releases/tag/v9.0.0>
=> Upgrade add-on base image to 9.0.0

base/config.json
Fixes the add-on slug, to prevent it from being published as the Alpine base image.
=> Fix add-on slug

base/Dockerfile
=> :arrow_up: Upgrades pip to 20.3.3

.github/workflows/deploy.yaml
The base images used already has them.
=> Remove Qemu user static binaries in deployment workflow

base/Dockerfile, base/build.json
Release notes: <https://github.com/hassio-addons/addon-base/releases/tag/v9.0.1>
=> Upgrade add-on base image to 9.0.1

base/Dockerfile, base/build.json
Upgrades the base image for this add-on to 9.1.2
=> Upgrade add-on base image to 9.1.2

base/Dockerfile, base/build.json
Release notes: https://github.com/hassio-addons/addon-base/releases/tag/v9.1.3
=> Upgrade base image to 9.1.3

base/Dockerfile
=> Upgrade Python pip to 21.0.1

base/Dockerfile, base/build.json
=> Upgrade base image to 9.1.4

base/Dockerfile, base/build.json
Upgrades add-on base image to v9.1.6
=> ⬆️ Upgrades add-on base image to v9.1.6

base/Dockerfile, base/build.json
Upgrades add-on base image to v9.1.7
=> ⬆️ Upgrades add-on base image to v9.1.7

base/Dockerfile, base/build.json
Upgrades add-on base image to v9.2.0
=> ⬆️  Upgrades add-on base image to v9.2.0

base/Dockerfile
=> ⬆️ Upgrades pip to 21.1.2

base/Dockerfile, base/build.json
Upgrades add-on base image to v9.2.2
=> ⬆️ Upgrades add-on base image to v9.2.2

base/Dockerfile, base/build.json
Upgrades base image to v10.0.0
=> ⬆️ Upgrades base image to v10.0.0

base/Dockerfile
https://pip.pypa.io/en/stable/news/#v21-1-3
=> ⬆️ Upgrades pip to 21.1.3

base/Dockerfile, base/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v10.0.1
=> ⬆️ Upgrades base image to v10.0.1

base/Dockerfile
=> ⬆️ Upgrades pip to 21.2.3

base/Dockerfile, base/build.json
=> ⬆️ Upgrades base image to 10.2.0

base/build.json, base/build.yaml, base/config.json, base/config.yaml
One file format to rule them all 🤷
=> Migrate JSON config to YAML

base/Dockerfile
Upgrades util-linux-dev to 2.37.2-r0
=> ⬆️ Upgrades util-linux-dev to 2.37.2-r0

base/Dockerfile
=> ⬆️ Upgrades pip to 21.3.1

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 10.2.1
=> ⬆️ Upgrades add-on base image to 10.2.1

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 11.0.0
=> ⬆️ Upgrades add-on base image to 11.0.0

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 11.0.1
=> ⬆️ Upgrades add-on base image to 11.0.1

base/Dockerfile
Upgrades expat-dev to 2.4.7-r0
=> ⬆️ Upgrades expat-dev to 2.4.7-r0

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 11.1.0
=> ⬆️ Upgrades add-on base image to 11.1.0

base/Dockerfile
Updates Python `pip` to 22.0.4
=> ⬆️ Upgrades pip to 22.0.4

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 12.0.0
=> ⬆️ Upgrades add-on base image to 12.0.0

base/Dockerfile, base/build.yaml
Upgrades add-on base image to 12.2.1
=> ⬆️ Upgrades add-on base image to 12.2.1

base/Dockerfile, base/build.yaml
=> ⬆️ Upgrades base image to 12.2.3

base/Dockerfile, base/build.yaml
=> ⬆️ Upgrades base image to 12.2.4

.github/dependabot.yaml, .github/renovate.json, base/Dockerfile
=> Add Renovate for dependency management
